### ISSUE TITLE
Attaching Metadata to Instances

### ISSUE THREAD

**Issue by PsypherPunk** [ukwa/w3act#260]
In the current system we script the creation of Instances and attach various metadata into the Instance's notes (see `/act/node/21886` as an example).

We need to be able to attach similar metadata to Instances in w3act. Ideally this should be more structured than the current large-text-blob.

**Comment by peterwebster** [comment]
@anjackson how does this impact on #231 ?

**Comment by anjackson** [comment]
They are complementary. #231 should ensure that basic Instance records are created quickly, but the crawl process may with to record information about an instance too. i.e. if the crawler script gets there first, it creates a new Instance with the QA data. If the Instance has already been created, it should update the existing instance with the QA data.

And as Roger says, in W3ACT this ought to be at least presented as a set of QA properties rather than a JSON blob, although given we already have that data imported, perhaps we'll have to store it like that.

**Comment by peterwebster** [comment]
Let's discuss this in our call tomorrow @anjackson : I'm not quite sure how to express the requirement, and how urgent it is

**Comment by anjackson** [comment]
This a new REST API, like the Targets one, for adding information about the crawl.

**Comment by peterwebster** [comment]
Some work to do in understanding possible changes to W3ACT data model to accommodate data incoming from Heritirix (rather than Monitrix as originally planned.)

**Comment by peterwebster** [comment]
@PsypherPunk it might be worth talking to Nicola about the requirements for this.

**Comment by nicolabingham** [comment]
@PsypherPunk @kinmanli I made some notes early on about the Heritrix crawl data we would need at instance level for QA. The requirement was basically for the reports to be similar to those we had in WCT. I'm not sure if they got brought in as requirements anywhere - I can't find them by searching on Github. Do you want the details in this ticket?

**Comment by PsypherPunk** [comment]
@nicolabingham, I think that would be useful, yes. Thanks.

**Comment by nicolabingham** [comment]
If it is possible to present summary information at instance level, the key elements would be:
Seed URL
Date and time crawl was scheduled.
Date and time crawl was actually started.
Elapsed time of crawl (in miliseconds)
Content downloaded in bytes
Number of URLs downloaded.
Number of URLs failed.

We also need the heritrix crawl logs as in WCT detailing all the requests made and HTTP response codes.

**Comment by peterwebster** [comment]
For info, they made it into the requirements docs on the ACT page wiki (v2 0), but were dependent on Monitrix, and so never made it into development. We didn't use Github for the initial requirements, it was more reactive. @nicolabingham

**Comment by nicolabingham** [comment]
@peterwebster Great, thanks for the info

**Comment by nicolabingham** [comment]
@anjackson the question of making crawl data, such as Heritrix crawl logs, available to Archivists for QA purposes came up in the WAT meeting yesterday. Currently we don't have the sort of information that we have in WCT and have to ask @PsypherPunk to look into the logs, for simple questions such as whether images have been downloaded (or whether there are issues in rendering them) etc. The curators are turning their attention to the QA of collections in more detail now and there are issues that I am struggling to diagnose without the logs. 

We decided that it would make sense to initially look at the sort of information needed for QA, rather than how it will be presented in W3ACT, so it is fine if the crawl data is outside of the system for the time being. 

The requirement is only for the BL Archivists to view this data and to expand it to other Archivists (NLW and NLS) later if we can successfully manage this. The QA process in W3ACT is that Expert_Users or Users do a first line of QA, flagging issues for the attention of Archivists to diagnose.  I don't envisage making crawl data available to Expert_Users through W3ACT, as it would involve a very high level of support from the Archivists and technical colleagues. 

Some ideas that came up were:
@GilHoggarth mentioned the possibility of exposing crawl data from (?) Cabana?
@PsypherPunk mentioned the possibility of adding NJB to the w3sysadmin mailing list to see crawl information. 
@PsypherPunk also mentioned that crawl information may be on a per job rather than per instance basis
It would be good if we could take this forward, cheers.

**Comment by nicolabingham** [comment]
@PsypherPunk also mentioned QA in Proxy mode for more complicated sites such as FaceBook. I explored this a while ago but it would be good to revisit it when it is up and running.

**Comment by GilHoggarth** [comment]
@anjackson Sounds like this should be created as it's own github ticket as it doesn't (to my understanding) seem central to this particular ticket.

**Comment by anjackson** [comment]
Currently adding:

```
    /** Crawl metadata */
    public String crawl_seeds;
    public Date crawl_scheduled_start_date;
    public Date crawl_actual_start_date;
    public Long crawl_duration_millis;
    public Long crawl_bytes_downloaded;
    public Long crawl_urls_downloaded;
    public Long crawl_urls_failed;   
    public String crawl_additional_information;
```

**Comment by anjackson** [comment]
Now those fields should be accessible and modifiable via the API, but are not yet shown in the UI. Suggest we just show them but do not allow them to be edited.

**Comment by niladreeb** [comment]
The fields are now visible in the UI and they are not editable.

**Comment by niladreeb** [comment]
Tested in actstage. Fields are visible and are not editable.

**Comment by niladreeb** [comment]
Retested and works fine

**Comment by GilHoggarth** [comment]
Andy, not sure how to test this ticket. Can you test this ticket please?

**Comment by anjackson** [comment]
I'm going to let @niladreeb check this one, if that's okay.

**Comment by niladreeb** [comment]
the metadata fields are now visible in the UI and are not editable. This much is now within test scope.

**Comment by GilHoggarth** [comment]
Nils, please test on /actstage.

**Comment by niladreeb** [comment]
Working fine on actstage.

**Comment by niladreeb** [comment]
Done on live
