### ISSUE TITLE
'nevercrawl' Should Visible to 'archivist' Only

### ISSUE THREAD

**Issue by PsypherPunk** [ukwa/w3act#330]
The 'nevercrawl' schedule should be available only to `archivist` users. This is specifically for Targets which we *absolutely must not crawl* rather than simply for Targets which we no longer want to crawl *frequently*.

**Comment by anjackson** [comment]
This is unfortunately a bit fiddly. If we exclude 'nevercrawl' from the list, then someone other than 'archivist' could overwrite it accidentally when editing other properties (because the select list does not really handle this case).

The ideal solution would be to pull if into a separate data field, but that means changing the data model, which I'm loath to do at this point. Alternatively, the editing process could validate the data, and the form would fail validation if a non-archivist attempted to change the frequency to or from 'nevercrawl'.

**Comment by PsypherPunk** [comment]
Did we suggest changing the name of the `nevercrawl` frequency to something like `blocked`? If it's better named it might mitigate some of the misuse cases.

**Comment by nicolabingham** [comment]
Yes, that would make things clearer from the user's perspective.

**Comment by GilHoggarth** [comment]
We’re now doing release testing on https://www.webarchive.org.uk/actstage!
Please test that the implementation of this ticket works correctly on /actstage – if it does, please label this ticket as “1 – Ready” and remove the “implemented” label.

**Comment by PsypherPunk** [comment]
Looks good to me.

**Comment by PsypherPunk** [comment]
All present and correct after the deployment.
