### ISSUE TITLE
Crawl depth set up as none

### ISSUE THREAD

**Issue by dorotawalker** [ukwa/w3act#403]
I think there’s another problem with Joan’s account. I’ve just noticed that some of her records have in the view mode ‘depth’ as none https://www.webarchive.org.uk/act/targets/act/act-1745066024703868039#crawlpolicy. When clicked on the edit mode it brings the default ‘Capped 500MB’ https://www.webarchive.org.uk/act/targets/act/act-6101449701777884753#crawlpolicy. I don’t even have an option as depth ‘none’.
It seems to be a display issue in View mode, as when you go into Edit mode the correct capping level is displayed.

**Comment by anjackson** [comment]
@niladreeb A depth of None should not happen. Can you see if you can ensure that, please?

**Comment by niladreeb** [comment]
Sure @anjackson. Replaced the None logic( when the default values are null ) with the first value of the lists.

**Comment by niladreeb** [comment]
Working fine in actstage.

**Comment by niladreeb** [comment]
Retested and acts fine.

**Comment by GilHoggarth** [comment]
Me, test.

**Comment by GilHoggarth** [comment]
I suspect the problem here is more likely to be incorrect data, probably imported into the system when the import mechanism didn't fully work, rather than an issue with W3ACT itself. I've tested using an expert and a normal user an neither has a problem with this. Consequently ticket passed.

**Comment by GilHoggarth** [comment]
Me, test.

**Comment by GilHoggarth** [comment]
Searched W3ACT postgres database and found an example of a target that has no depth set - 29984. However, when viewed via W3ACT this value is now displayed as "Capped (small - 500MB)". That is, Nils has implemented the code so that a null value is displayed as "Capped (small...".

There are 641 targets in the database that have no depth set - a new ticket should be created if these records should be updated to set the default value in the database.

**Comment by GilHoggarth** [comment]
This target, ID 29984, still has no depth set in the live postgres database. But in the UI View mode this is shown as "Capped (small - 500MB)" and when Edit mode is selected this value also defaults to the same small cap.
