### ISSUE TITLE
OpenWayback query strings altered during proxy

### ISSUE THREAD

**Issue by PsypherPunk** [ukwa/w3act#409]
Slightly covered [here](https://github.com/iipc/openwayback/issues/273) in an erroneous ticket for OpenWayback, w3act appearing to be altering query strings when proxying requests for OpenWayback.

For instance, this URL:

    http://www.rpg-resource.org.uk/index.php?article=1229&visual=1

...appears in the Tomcat logs as this:

    192.168.45.32 - - [07/Aug/2015:11:44:52 +0100] "GET /wayback/20150309193325/http://www.rpg-resource.org.uk/index.php?visual=1&article=1229 HTTP/1.1" 404 8123

Note that the query parameters have been reversed. URLs need to be passed through _as-is_.

**Comment by anjackson** [comment]
Can you test this at some point please?

**Comment by anjackson** [comment]
Hang on, it's definitely not right. Just a mo.

**Comment by anjackson** [comment]
Right, frustratingly, the WS library always uses a HashMap for query parameters, so ordering cannot be guaranteed. I've switched it to Http Client.

**Comment by anjackson** [comment]
@niladreeb You should be able to try it now.

**Comment by niladreeb** [comment]
Ok I'll look into it. Thanks.

**Comment by niladreeb** [comment]
In my local system after adding the target, when I open the QA Wayback, the url remains unaltered and the resource is shown properly in Legal Deposit QA Open Wayback.

**Comment by anjackson** [comment]
I think this is implemented then, and is ready for testing on actstage, right?

**Comment by anjackson** [comment]
So, something really weird on actstage. This is in the logs:

    2015-08-13 11:53:23,749 [warn] o.a.h.c.p.ResponseProcessCookies - Invalid cookie header: "Set-Cookie: PLAY_FLASH=; Max-Age=-86399; Expires=Wed, 12 Aug 2015 10:53:24 GMT; Path=/actstage; HTTPOnly". Negative max-age attribute: -86399

Which is correlated with specific resources not getting played back correctly, ending with a login page instead of the actual content. As of yesterday, this worked (in that the HTML came back - some of the underlying resources suffer the same issue)

https://www.webarchive.org.uk/actstage/wayback/20150526110116/http://bbc.co.uk/

But this does not  (gets a login page):

https://www.webarchive.org.uk/actstage/wayback/20150526110116/http://static.bbc.co.uk/

It seems to affect non-200 reponses mostly?  The PLAY_SESSION ID seems totally fine.

**Comment by niladreeb** [comment]
Working fine in actstage.

**Comment by niladreeb** [comment]
Retested and acts fine.

**Comment by GilHoggarth** [comment]
Andy, please test this ticket.

**Comment by anjackson** [comment]
Tested on actstage and it works.

**Comment by GilHoggarth** [comment]
Andy, please test on /actstage.

**Comment by anjackson** [comment]
Tested - all working fine now.
