### ISSUE TITLE
Unable to untick the box for the NPLD criteria 

### ISSUE THREAD

**Issue by dorotawalker** [ukwa/w3act#441]
Unable to untick the box for the NPLD criteria ticked by another user, so if someone ticked incorrect that the url meets the criteria, I am unable to overwrite it. I can add 'No LD Criteria Met', but the NPLD Scope at the top of the target record is still with (+):

https://www.webarchive.org.uk/act/targets/29217
https://www.webarchive.org.uk/act/targets/29340

**Comment by niladreeb** [comment]
Similar to https://github.com/ukwa/w3act/issues/424. The issue is resolved and tested in actstage.

**Comment by GilHoggarth** [comment]
Dorota, please test this ticket.

**Comment by dorotawalker** [comment]
This does not seem to be working. The record https://www.webarchive.org.uk/actstage/targets/29217 has three ticks in the NPLD criteria. The site is out of scope and the selector put the justification incorrectly, but when trying to untick the address and the professional judgement, the changes are not saved and the message is 'One of the checks for NPLD permission has been passed. Please unselect the 'No LD Criteria Met' field and save again'. It works fine when I untick the 'No LD Criteria Met' box.

**Comment by nicolabingham** [comment]
As commented by @dorotawalker this is not working as expected. Changes to NPLD made in edit mode (e.g. unchecking the postal address box) are not saved or are saved inconsistently.

**Comment by nicolabingham** [comment]
After speaking with @niladreeb it seems the issue is that the additional information boxes (postal address URL, correspondence and professional judgment notes) also need to be cleared as well as the boxes unchecked. Will add notes to explain this to users as follows: 
'If unchecking the UK Postal address/Correspondence/Professional Judgement boxes, the corresponding notes fields should be cleared otherwise your changes will not be saved'. 
..this raises the issue of the general confusion of this form which I think could be mitigated with a better layout, i.e. linking the checkboxes and information fields more strongly but this will be for another time....

**Comment by niladreeb** [comment]
A new ticket https://github.com/ukwa/w3act/issues/448 has been raised to address the issue properly.
