### ISSUE TITLE
Start date default to be changed

### ISSUE THREAD

**Issue by dorotawalker** [ukwa/w3act#451]
The start date default is currently set to the day at 9am, e.g. today is 16th Sep and the calendar is set for 16th Sep at 9am. When setting a crawl frequency, for most users the 9am is already in the past. If a user does not notice that and sets, for example the annual frequency, the site will not be crawled for another year. Could we change the default to either the next day 9am or the time in the evening after the end of the working day?

**Comment by anjackson** [comment]
Unfortunately, the way things are set up at the moment, changing this won't generally make much difference due to the way crawls are scheduled.  When you pick a start date and end date, you are defining the period over which the frequent crawls will take place, but *not* the actual scheduled launch time.

Daily crawls are always launched at 12 noon each day, weekly crawls are launched on the first day of the week at a fixed time. Monthly crawls on the first day of the month, and so on.  This is not what we would prefer, but Roger was unable to get Heritrix (and our management of it) to scale up to handling thousands of different crawls with different crawl schedules all at once. Doing so will involve quite major upheaval to our crawlers and all the downstream processes.

**Comment by dorotawalker** [comment]
@anjackson What about the six monthly and annually? Are they starting on 1st Jan and 1st July?

**Comment by anjackson** [comment]
I believe so, thought I'll ask @GilHoggarth to double check that.

**Comment by dorotawalker** [comment]
Interesting. But there are examples of crawling on the day I've set it up to be or the day after e.g. six-monthly crawl here https://www.webarchive.org.uk/act/targets/30439. In this case it couldn't have been captured automatically as the site doesn't meet the automatic NPLD criteria.

**Comment by dorotawalker** [comment]
Sorry wrong button. Didn't mean to close it.

**Comment by anjackson** [comment]
Well, this might be different problem - we did (and I think we still do) have hooks that attempt to ensure any new Targets added to W3ACT are captured ASAP in a shallow crawl as a one-off. I fear this mechanism may be firing even if there is no crawl license.

**Comment by GilHoggarth** [comment]
Sixmonthly and annually - yes, ran on Jan and Jul 1.

**Comment by nicolabingham** [comment]
When scheduling with Heritrix is more mature the requirement will be to set monthly, six-monthly and annual targets to start on different days/months depending on the target. 

The time of day that a daily crawl starts is less of an issue. It may be that removing the option to set a time of day for the daily crawl is better.  @dorotawalker would you be happy with this? It would save time completing the scheduling and would be less confusing. We would need to communicate this to users within the tool.

**Comment by anjackson** [comment]
So, the new crawl dynamics do allow launching crawls at any hour, so that should be fine. I'll alter the code to default to the following day, and to warn if the start date is in the past.

**Comment by GilHoggarth** [comment]
Closing, seen to be done.
