### ISSUE TITLE
status of the Open UKWA when changing manually

### ISSUE THREAD

**Issue by dorotawalker** [ukwa/w3act#455]
When changing manually the status in the Open UKWA tab from Granted to Not Initiated, the tab on top still shows the green (+) sign.

**Comment by anjackson** [comment]
The status is indicated by whether there is a License currently selected for the Target. There does not have to be a full crawl permission, because in the future we also accept Targets with licenses that are obtained outside of W3ACT (like the NLS/NLW ones).

**Comment by dorotawalker** [comment]
https://www.webarchive.org.uk/act/targets/30367

**Comment by nicolabingham** [comment]
@dorotawalker thanks. 

@anjackson we changed the Licence status in the Target record but did not do anything with the crawl permissions: https://www.webarchive.org.uk/act/target/30367/crawlpermissions 
Should we also change the status of the crawl permissions to reflect that we do not have a licence?

**Comment by anjackson** [comment]
So, to remove the green (+), you should only need to de-select the license field on the target editing page.  That item currently has two 'invented licenses', so that should be changed to 'None'.

Presumably, this crawl permission was in error? It should probably be deleted in that case? i.e. whether you want to keep the 'old' crawl permission depends on whether you want to keep it as a record (but maybe mark it as expired), or just delete it.

**Comment by nicolabingham** [comment]
@dorotawalker could you try to make these edits please.

**Comment by dorotawalker** [comment]
@nicolabingham that seem to have worked. If the selection of 'Not initiated' status doesn't trigger/can't trigger the change of the licence to 'None', perhaps it's worth outting in the user guide it's a two step process?

**Comment by nicolabingham** [comment]
@dorotawalker thanks. I will put this in the user guide. Are you happy to close this ticket?

**Comment by dorotawalker** [comment]
@nicolabingham yes, I will do that.
