### ISSUE TITLE
Single sign-on is too successful

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#470]
When a user logs into ACT they are simultaneously logged into ACT-DDHAPT. Single sign-on is fine with all production systems, but this is crossing production with testing. We need to modify the cookie scoping so that this doesn't happen.

**Comment by chrispeacockbl** [comment]
I cannot seem to reproduce this with ACT / ACT-DDB. 

Was this specifically only with ACT-DDHAPT?

**Comment by chrispeacockbl** [comment]
I think this might possibly not / no longer be a bug. Examining the cookies for the Production and Beta environments shows that they are distinct by path and I am prompted to log into a system after logging into the other one. 

Note that the login cookie persists within a browser session, so that if you e.g. log into Production and then log into Beta, and then navigate back to Production, you will still be logged in to Production also. Could this be what happened originally?
