### ISSUE TITLE
Target Collection Change is not always Saved

### ISSUE THREAD

**Issue by ldbiz** [ukwa/w3act#495]
When editing a Target's metadata and changing the collection, in some circumstances it does not change, and there is no message to show why.

Example: 
Sir Francis Drake Primary School > Edit Collection > Untick Smashfest > Save > Has no effect.

I've checked to see if there are instances of the target belonging to the collection; there are not. I don't know if it is because assigning no collection is not allowed (correctly or incorrectly).

Noticed, while testing the fix for #484

**Comment by ldbiz** [comment]
The save produces a message confirming the update; there are no other messages, and when viewing the collection again, it is set, which is not expected.

**Comment by anjackson** [comment]
So, I think the issue here is that the Collections in the form become NULL, rather than False. There are other cases, like on/off checkboxes, where to unset the value you have to look for the value having disappeared rather than being set to false. It's quite annoying.

So, the solution should be that when the TargetController is updating the Target, it needs to remove all Collections if the corresponding form field is unset/NULL.

**Comment by ldbiz** [comment]
[Committed](https://github.com/ukwa/w3act/commit/1a5dab3a2578467d73d913f001918aaeebefdd89). Also fixed same issue for Target Subjects.
