### ISSUE TITLE
Ability to force refresh of derived fields

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#594]
When modifying the underlying database directly, the 'derived' fields can become out of sync with the fields they derive their values from. e.g. importing a '.uk' site directly does not automatically set the corresponding 'in NPLD scope' flag. 

This can be done manually, via the UI, by just editing and re-saving the entry, but we should really have a way for flush/sync the derived fields.

**Comment by anjackson** [comment]
Problem is this is potentially slow, so we need to run it in the background. i.e. an endpoint to launch the job (if not running) and to check the status of the job.

**Comment by crarugal** [comment]
Example target: https://www.webarchive.org.uk/act/targets/73966


![image](https://user-images.githubusercontent.com/18530934/53089416-6f99c300-3504-11e9-9adf-833fd911c973.png)

**Comment by crarugal** [comment]
Here's a list of the migrated targets where the majority are out of NPLD scope, I think these are all the migrated records.
[No NPLD.xlsx](https://github.com/ukwa/w3act/files/2884465/No.NPLD.xlsx)

**Comment by min2ha** [comment]
@crarugal thanks for adding more details.

But I need to understand what do you expect to see on **NPLD scope**?
If it's just green color plus sign (+) at the **NLPD scope** tab? Or something more than that? Or some fields need to be checked at the _**NPLD scope form**_ according to data in Excel file?

![image](https://user-images.githubusercontent.com/15713396/53108659-50645b00-352f-11e9-872c-01ed0a3f3216.png)

**Comment by crarugal** [comment]
Ideally the NPLD scope should have a green + sign if the UKWA licence has been granted, I think as Andy mentioned, re-saving the record and re-syncing derived fields are able to update "NPLD scope" to its correct state. I'm not entirely sure what triggers this change, could it be only a background "UK top-level domain" check?

I don't think re-saving a target works for all the records, re-saving the following target still doesn't produce a green + sign: http://www.jimallister.org/ (maybe because it doesn't pass "UK top-level domain" check)
https://www.webarchive.org.uk/act/targets/76162
![image](https://user-images.githubusercontent.com/18530934/53164968-645c9b00-35c9-11e9-906e-c10406c2ab2f.png)

Of th 8k/9k migrated targets, I'm not sure how many would pass the "UK top-level domain" check.



If syncing derived fields and re-saving the record doesn't fix the NPLD scope (even if the record has been a granted licence) then I'm not sure which other NPLD scope tests can be set to true because the majority are already false. 
![image](https://user-images.githubusercontent.com/18530934/53166606-b7385180-35cd-11e9-8410-d1617044be7c.png)

Also I'm not sure whether or not these NPLD scope tests were used in WCT.

**Comment by anjackson** [comment]
In terms of implementation, we need to run this for every Target:

https://github.com/ukwa/w3act/blob/2ad1dfd7474cf51a4f646c7cef438911297061f4/app/controllers/TargetController.java#L895-L896

If we try to do this in a single Controller it'll probably take too long. So, one option would be to clone or extend this code:

https://github.com/ukwa/w3act/blob/2ad1dfd7474cf51a4f646c7cef438911297061f4/app/controllers/TargetController.java#L558-L570

This allows the Targets to be downloaded page by page. We could add a `runChecks` option that would execute `runChecks()` and then `update()` while it builds the response. An external client could then force this update while downloading the Targets as JSON.

**Comment by min2ha** [comment]
@anjackson as discussed optional flag parameter added, if true, then sync all active targets (includes `runChecks` and `Update` for each. Beware it's very time consuming refresh, which may take more than 2hrs with 80K targets (on single dev desktop))

**Comment by crarugal** [comment]
The forced refresh seems to have worked, but only for 2/3 thirds of the roughly 9k affected records. It looks as though two automated check were carried out (UK Hosting and UK top-level domain); the ~6k records that are now within NPLD Scope because they pass either one of these automated checks.

But there are ~3k records that are still outside of NPLD scope and I believe it is because they are not .uk sites and so the automated checks don't work. It looks like the effected targets have seed URLs ending in .com, .org etc.

Attached is an excel spreadsheet of the ~3k records, and also another tab for the full list of ~9k records where you can compare the refreshed Beta records and current production records
[No NPLD after refresh.xlsx](https://github.com/ukwa/w3act/files/3043137/No.NPLD.after.refresh.xlsx)

**Comment by anjackson** [comment]
On what grounds are these in scope for NPLD?

Or, given they have a WCT-era licence, should we crawl them under those terms instead?

**Comment by nicolabingham** [comment]
These sites were crawled with permissions held in two databases, an Access db held on the shared drive and the Selection Permission Tool. They can all be brought across as "Professional Judgement", with the text "Sites migrated from WCT"

**Comment by anjackson** [comment]
I'm refactoring this as per:

> This allows the Targets to be downloaded page by page. We could add a runChecks option that would execute runChecks() and then update() while it builds the response. An external client could then force this update while downloading the Targets as JSON.
