### ISSUE TITLE
Right Click on Collection to open it in new tab doesn't work

### ISSUE THREAD

**Issue by ldbiz** [ukwa/w3act#595]
If I right click on a collection node within the Collections tree and select Open in New Tab, it just opens the page as is in the new tab.

If I left click, it correctly opens the collection.

![image](https://user-images.githubusercontent.com/16339290/47645234-44135700-db68-11e8-8e8f-0d6f22fdf9e8.png)

**Left Click (correct)**
![image](https://user-images.githubusercontent.com/16339290/47645278-6a38f700-db68-11e8-8518-18aaf1cc2ad2.png)
https://www.webarchive.org.uk/act/collections/329

**Right Click > Open in New Tab (incorrect)**
![image](https://user-images.githubusercontent.com/16339290/47645298-7d4bc700-db68-11e8-9ff7-dd8bdfae1655.png)
https://www.webarchive.org.uk/act/collections/list?s=title#

Presumably the URL is incorrectly (or not) being captured in the latter case.

**Comment by min2ha** [comment]
Presumably full description of specific subject or collection is expected in new tab and not the list of targets in that specific subject or collection.

**Comment by crarugal** [comment]
https://beta.webarchive.org.uk/act/collections/list?s=title


Right clicking a collection will still take you to: https://beta.webarchive.org.uk/act/collections/list?s=title#
For example, opening the Brexit collection will open

![image](https://user-images.githubusercontent.com/18530934/60655477-b0f09680-9e45-11e9-9df6-d2ff208691ba.png)

Instead of taking you to https://beta.webarchive.org.uk/act/collections/910

**Comment by crarugal** [comment]
Right clicking a collection or a sub collection will work in the webarchive.org.uk/act/targets/list 
![image](https://user-images.githubusercontent.com/18530934/60657236-e2b72c80-9e48-11e9-9bc6-7c73a33b85be.png)

But currently does not work for webarchive.org.uk/act/collections/list?s=title

**Comment by min2ha** [comment]
Thanks for clarification where the problem existed. Fix is done and will be ready to test shortly.

**Comment by crarugal** [comment]
Works as expected
