### ISSUE TITLE
Mementos Protocol Issue

### ISSUE THREAD

**Issue by HelenaByrne** [ukwa/w3act#597]
This is an example of a search through the Time Travel interface that brings up a UK Web Archive hit:

http://timetravel.mementoweb.org/list/20131006095304/https://www.irishtimes.com/business/technology/net-results-lax-archival-law-allows-digital-black-hole-1.2644166 

![image](https://user-images.githubusercontent.com/43820507/48787311-6e2be500-ece0-11e8-9840-64b6147df7bf.png)

And when you click through you get this message:
![image](https://user-images.githubusercontent.com/43820507/48787343-7c7a0100-ece0-11e8-8677-ddaed21ca067.png)

But don't think it's consistent because I used Time Travel to look up this Irish Independent article and I thought it came up but it's not coming up now: http://timetravel.mementoweb.org/list/20150606095304/https://www.independent.ie/opinion/columnists/carol-hunt/constitutionally-women-are-still-breeding-machines-31248545.html

**Comment by anjackson** [comment]
I've reported this to [memento-dev](https://groups.google.com/forum/#!topic/memento-dev/YE4rt6L5ICg) as I think I'll need their help to debug it.

**Comment by HelenaByrne** [comment]
Thanks ☺

**Comment by machawk1** [comment]
I am unable to replicate the first screenshot by going through the Time Travel service, entering https://www.irishtimes.com/business/technology/net-results-lax-archival-law-allows-digital-black-hole-1.2644166 (as well as an identical date and time), and hitting the "Find" button.

I have never encountered the "Data not provided" listings in the interface. Perhaps someone on the Memento-dev list that has some hands-on experience of the code-behind-the-interface can shed some light.

**Comment by anjackson** [comment]
[This detailed explanation](https://groups.google.com/d/msg/memento-dev/YE4rt6L5ICg/yI42TQi7BgAJ) indicates that this can happen for two reasons:

- The aggregator has cached a true-positive hit for an item we have since blocked access to.
- The aggregator has generated a false-positive hit based on the Machine Learning algorithm they are using to predict which web archives hold which URLs.

The former does not apply here, so it seems the latter false-positives are the issue. Or, [as Michael Nelson put it](https://groups.google.com/d/msg/memento-dev/YE4rt6L5ICg/7lM5Hk67BgAJ):

> https://timetravel.mementoweb.org is telling you what your archive *should* have.
please update your holdings accordingly.  
> ;-)

TBH, I think this false-positive behaviour leads to a poor user experience, and due to the way the user flow works, will tend to lead to users 'blaming' the archives unfairly (as happened here). I'm going to feed that back and suggest an alternative approach.

**Comment by HelenaByrne** [comment]
Thanks Andy.
