### ISSUE TITLE
Open Access Permission Not Feeding Through to User Interface

### ISSUE THREAD

**Issue by HelenaByrne** [ukwa/w3act#601]
Some open access licence permissions are not coming through to the UI. If we take this top level domain record for Cats Protection: https://www.webarchive.org.uk/act/targets/75 (http://www.cats.org.uk/) the open access has fed through to the subdomain Target record : https://www.webarchive.org.uk/act/targets/17379 (http://www.cats.org.uk/what-we-do/manifesto-for-cats/) but if we look at the 2015 GE collection on the UI at this record it says viewable on library premises and brings your to ericom: https://www.webarchive.org.uk/en/ukwa/collection/142?page=2

![image](https://user-images.githubusercontent.com/43820507/49094397-12240c00-f25e-11e8-918b-b84835a66fdd.png)

**Comment by anjackson** [comment]
The site itself it available: https://www.webarchive.org.uk/wayback/archive/20150306094854/http://www.cats.org.uk/what-we-do/manifesto-for-cats/

So I think the issue is that the Solr index is being used to indicate availability, but this can lag significantly behind the current state of things, and requires a lot of work (re-indexing) to correct.

**Comment by anjackson** [comment]
Hm, actually, this information should be coming from the Collections Solr interface, which should be up to date. Looks like something else is wrong.

**Comment by anjackson** [comment]
The logic in ukwa-manage relies of the license text field, rather than looking at the `hasOpenAccessLicence` field. 

For targets that inherit their licence from a parent target, this failed because there is no licence array.  For targets undergoing permissions process, they have a licence (pending), and this is erroneously taken as a signal that it's OA.

This is a fairly small fix to ukwa-manage.

**Comment by anjackson** [comment]
I believe this is okay now. @HelenaByrne can you verify and close if all is well?

**Comment by HelenaByrne** [comment]
Thanks Andy.
