### ISSUE TITLE
Deleting duplicates belonging to different collections can't be done

### ISSUE THREAD

**Issue by emacglone** [ukwa/w3act#607]
I need to retag records from the WCT Scottish Government Collection, and delete superfluous records from the collection in ACT.
As I can't save changes to duplicates, so can't remove collection tags in order to delete superfluous records from ACT (those not carrying a licence), or retag WCT records (carrying the licence) as belonging to the ACT collection which appears in UKWA.

For example:
https://www.webarchive.org.uk/act/targets/72377 (from WCT)
https://www.webarchive.org.uk/act/targets/16706

**Comment by emacglone** [comment]
Just to be a little clearer: ACT doesn't allow targets attached to collections or licences to be deleted, or duplicates to be saved.
I have added records to ACT which duplicated (it seems quite a few) records in WCT. I need to be able to delete one, before I can save changes of any kind - but they will either have a collection, or licence attached.

**Comment by anjackson** [comment]
The problematic logic is here:

https://github.com/ukwa/w3act/blob/38d48e28dcfe7862979f10d67ef5bf99dfb70b71/app/models/Target.java#L2404-L2409

I think we need to delete all the instances, as they are not used, and will prevent deletion.

**Comment by crarugal** [comment]
https://beta.webarchive.org.uk/act/targets/72377 and https://beta.webarchive.org.uk/act/targets/16706 have the same pimary seed. 

In this example, target 72377 which was migrated from WCT will be kept as it has a licence and 16706 will be deleted.

Even though both exist with the same primary seed, the two have slightly different primary seeds with one that ends in a forward slash, which means they can both be edited and saved; unlike other targets with the exact same primary seed URL.

![image](https://user-images.githubusercontent.com/18530934/60278710-d4708a00-98f7-11e9-9bc8-7cc9379ecad6.png)

You can successfully delete target 16706
![Screenshot 2019-06-27 16 11 36](https://user-images.githubusercontent.com/18530934/60278772-ef42fe80-98f7-11e9-8495-bd2b31bbe537.png)

Another example of a clash of duplicate primary seeds is: webarchive.org.uk/act/targets/72678 and https://beta.webarchive.org.uk/act/targets/72679.
![Screenshot 2019-06-27 16 31 17](https://user-images.githubusercontent.com/18530934/60279485-0a623e00-98f9-11e9-83de-22d20592409e.png)

You will be unable to edit https://beta.webarchive.org.uk/act/targets/72679 because it points to the same URL as https://beta.webarchive.org.uk/act/targets/72678. The same will be true of 72679.

![Screenshot 2019-06-27 16 32 53](https://user-images.githubusercontent.com/18530934/60279608-4bf2e900-98f9-11e9-8cc0-532d66ca7d01.png)



After deleting 72679, it is now possible to edit and save target 72678
![Screenshot 2019-06-27 16 35 09](https://user-images.githubusercontent.com/18530934/60279778-996f5600-98f9-11e9-9df9-4ea80abbaba7.png)

![Screenshot 2019-06-27 16 37 34](https://user-images.githubusercontent.com/18530934/60279966-f539df00-98f9-11e9-8ef5-2e749107c714.png)


Another example is https://beta.webarchive.org.uk/act/targets/13671 and https://beta.webarchive.org.uk/act/targets/72375.  
![image](https://user-images.githubusercontent.com/18530934/60280492-eef83280-98fa-11e9-9141-dc994fc5bad1.png)

The issue here is perhaps more curatorial, a decision has to be made as to which to delete. The curator will have to decide which metadata (and possibly the seeds too) to bring across to the duplicate target.
![image](https://user-images.githubusercontent.com/18530934/60280661-44344400-98fb-11e9-8018-3f8009a3cfc8.png)

**Comment by min2ha** [comment]
@crarugal, we had a chat about it with @nicolabingham, so actually the curator only is well familiarised with specific collection and it is up on her/him which duplicate target should be chosen to delete. Anyway preserved data remains untouched.

**Comment by crarugal** [comment]
Thanks @min2ha and @nicolabingham, should I close it as it the solution works.

**Comment by min2ha** [comment]
@crarugal yes, I think we should close at the moment. Thanks
