### ISSUE TITLE
Implement the higher level subject taxonomy on ACT and the website 

### ISSUE THREAD

**Issue by nicolabingham** [ukwa/w3act#629]
The LDWASG have agreed the higher level subject taxonomy for the Topics and Themes page, https://webarchive.org.uk/en/ukwa/collection 
It needs to be implemented in ACT so the curators can assign collections into the higher level taxonomy. It will then need implementing on the topics and themes page. This will need some design work and will need a separate ticket on the UI GitHub page. 
The taxonomy is: 
Science; Technology & Medicine; Sport & Recreation; History; Politics & Government; Arts & Culture; Places; Society & Communities; Currently Working On. 
Curators should ideally be able to assign the higher level taxonomy from the Collections list page in ACT.

**Comment by anjackson** [comment]
Following conversation with @nicolabingham, this needs to be:

- A new _Collections Subject Area_ field, distinct from the subjects used for Targets.
- Must allow multiple values to be selected.
- Is a required field, i.e. a value must be given when a Collection is edited. (Or, at least, when a top-level Collection is edited?)

Probably easiest to implement in W3ACT directly for now.

**Comment by nicolabingham** [comment]
Thanks @anjackson I will check with the LD WA Metadata Working Group about thier understanding of this.

**Comment by min2ha** [comment]
New _higher level hierarchy tree node_ (aka **higher level subject taxonomy**) in Collection Tree will be another new Top Level Collection (i.e. who has no parent). Complexity and size of data structure will significantly increase if existing collections could be assigned to **higher level subject** from different sublevels of different top level collections. Same sub collection may exist in different **higher level subjects**. Inherited sub collections will be assigned to **higher level subject** by default because of parent collection belonging to that **higher level subject**.

Is it acceptable?

**Comment by nicolabingham** [comment]
Thanks @min2ha 
The summary is accurate, however, the new higher level taxonomy for collections will be different/separate from the existing subject level taxonomy.

**Comment by anjackson** [comment]
As [I suggested before](https://github.com/ukwa/w3act/issues/629#issuecomment-553469126) - I think we can extend the existing fragments of a [`collection_areas`](https://github.com/ukwa/w3act/blob/ae2fc7c329a21b440b020b44a6b00bf4bc1a3a8f/app/models/TaxonomyType.java#L27) taxonomy.

I expect this to work by extending the Collections editor, so that when a top-level Collection is edited, it must be given a `Collection Area`, which corresponds to a new taxonomy which is associated with the Collection in the same manner as a Target can be associated with a Subject.

To support this we will likely need to add a `CollectionAreaController` so we can support viewing and updating this new taxonomy, as is done for the existing collections/subjects/etc.

**Comment by min2ha** [comment]
I've just checked, and we already have 37 `collection_areas` so to speak, excerpt below:

<img width="939" alt="Screenshot 2019-12-18 at 17 32 55" src="https://user-images.githubusercontent.com/15713396/71109240-b441c980-21bc-11ea-9125-ca4ee839362b.png">

**Comment by anjackson** [comment]
Implementation that uses this information is being covered by https://github.com/ukwa/ukwa-ui/issues/257
