### ISSUE TITLE
Problems with editing some Targets following 2.2.0 release

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#633]
Some targets cannot be edited under 2.2.0. Main problem appears to arise with multiple URL targets, perhaps related to changes to how lists are handled.
e..g if we try to change https://beta.webarchive.org.uk/act/targets/34937 to make the URL list consistent with PROD, i.e.:

```
http://www.craftscouncil.org.uk/, https://www.craftscouncil.org.uk/sitemap.xml
```

Saving gives a NPE.  I suspect we need to avoid using the same splitting mechanism for URLs that we use for collections etc.?

**Comment by nicolabingham** [comment]
This appears to be resolved now on Beta. I edited http://www.craftscouncil.org.uk/ and some other targets with no errors.

**Comment by crarugal** [comment]
I tried editing https://beta.webarchive.org.uk/act/targets/78227/ and I'm getting time outs, but this issue is also present in production and has been present for some time.

It seems that adding additional URLs no longer produces NullPointerExceptions.

There was one oddity, but I have yet to investigate it further: 
![image](https://user-images.githubusercontent.com/18530934/69439082-24843900-0d3e-11ea-89bf-ad8e2471e7de.png)
The craftcouncil sitemap url was already present in another unrelated record; I checked my web history and I have never visited beta.webarchive.org.uk/act/targets/30839, it could be human error and added by mistake but I'm not sure
