### ISSUE TITLE
Replace comma in CSV exports with a tab

### ISSUE THREAD

**Issue by anjackson** [ukwa/w3act#681]
The current export code writes out CSV, but does not handle escaping of commas at all!  To fix this properly, a CSV writing library should be used, and all the CSV export code re-written.

Alternatively, while the export code is not well-written in general, it does at least appear to use a specific variable for the CSV SEPARATOR, rather than having commas everywhere:

https://github.com/ukwa/w3act/blob/6ad35fff95854edd847c279904534938ff73295d/app/uk/bl/Const.java#L358-L359

As an interim measure, we could just replace that with a `\t` tab. That should fix all CSV outputs immediately, as long as everyone who uses those outputs is aware of the change.

**Comment by min2ha** [comment]
As per [RFC 4180](https://www.ietf.org/rfc/rfc4180.txt):

    Fields containing line breaks (CRLF), double quotes, and commas should be enclosed in double-quotes.

Examples: 
"Anglo Nubian Goat Society, The"
Bat Ecology and Bioacoustics Lab

**Comment by crarugal** [comment]
testing: https://dev.webarchive.org.uk/act/targets/list, looking at "100 Best Sites" collection: 
![image](https://user-images.githubusercontent.com/18530934/198345471-db9dc8c8-6611-431c-99ed-6a45da0ae3e9.png)

**Original csv export:**
![image](https://user-images.githubusercontent.com/18530934/198345738-76038721-4864-4fc4-95d7-a9e387002a98.png)

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Work/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Work/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



nid | title | field_url | author | field_crawl_frequency | created |   |  
-- | -- | -- | -- | -- | -- | -- | --
2902 | 38 Degrees | https://speakout.38degrees.org.uk/ | https://you.38degrees.org.uk/ | http://www.38degrees.org.uk/ | Nicola Bingham | QUARTERLY | 2013-07-22T15:02:52Z
2963 | Air BnB | https://www.airbnb.co.uk/ | https://www.airbnb.co.uk/sitemaps | Nicola Bingham | MONTHLY | 2013-07-24T13:30:41Z
2984 | Amazon | https://www.amazon.co.uk/ | https://www.amazon.co.uk/gp/site-directory?ie=UTF8&ref_=nav_shopall_fullstore | Nicola Bingham | DAILY | 2013-07-25T13:02:14Z
2904 | Anarchist Federation | http://www.afed.org.uk/ | Nicola Bingham | SIXMONTHLY | 2013-07-22T15:15:47Z
2983 | Argos.co.uk | http://www.argos.co.uk | Nicola Bingham | WEEKLY | 2013-07-25T12:57:13Z
2974 | Artsthread | http://www.artsthread.com/ | Nicola Bingham | QUARTERLY | 2013-07-25T09:30:46Z



</body>

</html>


**Dev csv export:**
![image](https://user-images.githubusercontent.com/18530934/198345992-7a79747d-e38f-43fd-9e4f-cadb731b2184.png)

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Work/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Work/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



nid	title	field_url	author	field_crawl_frequency	created |   |  
-- | -- | --
2902	38   Degrees	https://speakout.38degrees.org.uk/ | https://you.38degrees.org.uk/ | http://www.38degrees.org.uk/	Nicola   Bingham	QUARTERLY	2013-07-22T15:02:52Z |  
2963	Air BnB	https://www.airbnb.co.uk/ | https://www.airbnb.co.uk/sitemaps	Nicola   Bingham	WEEKLY	2013-07-24T13:30:41Z |  
2984	Amazon	http://www.amazon.co.uk/ | https://www.amazon.co.uk/gp/site-directory?ie=UTF8&ref_=nav_shopall_fullstore	Nicola   Bingham	DAILY	2013-07-25T13:02:14Z |  
2904	Anarchist   Federation	http://www.afed.org.uk/	Nicola   Bingham	SIXMONTHLY	2013-07-22T15:15:47Z |   |  
2983	Argos.co.uk	http://www.argos.co.uk	Nicola   Bingham	WEEKLY	2013-07-25T12:57:13Z |   |  
2974	Artsthread	http://www.artsthread.com/	Nicola   Bingham	QUARTERLY	2013-07-25T09:30:46Z |   |  



</body>

</html>



Tabbed export fails

**Comment by crarugal** [comment]
Just realised it exported as .csv, which is why it failed to parse as expected. Saving the file as .tsv works:
![image](https://user-images.githubusercontent.com/18530934/199210652-ab249e54-34a4-422f-9b36-1bf60f5568d2.png)

<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/Work/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/Work/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



nid | title | field_url | author | field_crawl_frequency | created |  
-- | -- | -- | -- | -- | -- | --
2902 | 38 Degrees | https://speakout.38degrees.org.uk/,https://you.38degrees.org.uk/,http://www.38degrees.org.uk/ | Nicola Bingham | QUARTERLY | 2013-07-22T15:02:52Z
2963 | Air BnB | https://www.airbnb.co.uk/,https://www.airbnb.co.uk/sitemaps | Nicola Bingham | WEEKLY | 2013-07-24T13:30:41Z
2984 | Amazon | http://www.amazon.co.uk/,https://www.amazon.co.uk/gp/site-directory?ie=UTF8&ref_=nav_shopall_fullstore | Nicola Bingham | DAILY | 2013-07-25T13:02:14Z
2904 | Anarchist Federation | http://www.afed.org.uk/ | Nicola Bingham | SIXMONTHLY | 2013-07-22T15:15:47Z
2983 | Argos.co.uk | http://www.argos.co.uk | Nicola Bingham | WEEKLY | 2013-07-25T12:57:13Z
2974 | Artsthread | http://www.artsthread.com/ | Nicola Bingham | QUARTERLY | 2013-07-25T09:30:46Z
3002 | Barbican | http://www.barbican.org.uk/,https://www.barbican.org.uk/sitemap.xml?page=1,https://www.barbican.org.uk/sitemap.xml?page=2,https://www.barbican.org.uk/sitemap.xml?page=3 | admin | MONTHLY | 2013-07-25T21:06:20Z



</body>

</html>


We might have to export as .tsv as default, instead of .csv

**Comment by nicolabingham** [comment]
Works on dev

**Comment by crarugal** [comment]
I exported 
![image](https://user-images.githubusercontent.com/18530934/201663210-b750dc08-c1b3-42b3-a63c-0c863f13248a.png)
Which is automatically saved in download as:
![image](https://user-images.githubusercontent.com/18530934/201663298-f8279f17-d2eb-4c5a-aa25-cf6480a3a134.png)

However, this format still causes issues. Trying to import to excel, in original file format:

**Comma separated**
![image](https://user-images.githubusercontent.com/18530934/201663598-0cfad4ab-55b9-4913-880d-7b53ac8a4747.png)


**Tab separated:**
![image](https://user-images.githubusercontent.com/18530934/201663659-e1cc55fd-728f-4a85-9be7-3394cf54fd01.png)

The previous solution worked well, but needed to be exported as .TSV

**Comment by crarugal** [comment]
Exporting this collection to test outputs:
![image](https://user-images.githubusercontent.com/18530934/203381752-d5646de8-b672-4b8d-b905-4589e113b1ab.png)


**Exporting as CSV:** I'm not sure if this is desired behaviour, but opening up in excel, we can see that the data doesn't match the headers:
![image](https://user-images.githubusercontent.com/18530934/203381543-82e125d1-d2ef-4384-bcc0-1e003895a7e5.png)

**Exporting as TSV: this works as expected**
![image](https://user-images.githubusercontent.com/18530934/203382058-28dc0ed5-4e76-470d-abe7-f1cfd5d3305d.png)

**Exporting as JSON: formatted as expected:**
![image](https://user-images.githubusercontent.com/18530934/203382344-9747bb8c-da37-4f0b-87a7-b6e42154c1ab.png)

**Comment by crarugal** [comment]
The exports are really good, the only thing I'm not sure of is the CSV export. It works as expected, but perhaps it can never be parsed as we would hope, due to the multiple secondary seeds that are separated by commas. I think this should still pass as a fix because the TSV and JSON exports are better formats which work. Trying the exports on large collections, such as Brexit, also works perfectly. Thanks, @min2ha

**Brexit TSV:**
![image](https://user-images.githubusercontent.com/18530934/203383273-7abfeb6c-b2bf-46fd-ac28-8702da225d94.png)

**Brexit JSON:**
![image](https://user-images.githubusercontent.com/18530934/203383526-968b5f03-e038-4363-a693-798a1cc52521.png)
